from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from io import BytesIO
from datetime import datetime


def generate_report(data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title = ParagraphStyle('t', fontSize=20, fontName='Helvetica-Bold', spaceAfter=6)
    subtitle = ParagraphStyle('s', fontSize=10, textColor=colors.grey, spaceAfter=12)
    heading = ParagraphStyle('h', fontSize=13, fontName='Helvetica-Bold', spaceBefore=14, spaceAfter=6)
    body = ParagraphStyle('b', fontSize=9, leading=14)

    story = []

    story.append(Paragraph("Security Scan Report", title))
    story.append(Paragraph(f"Target: {data.get('url')}", subtitle))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", subtitle))
    story.append(HRFlowable(width="100%", thickness=1, spaceAfter=10))

    score = data.get('score', 0)
    risk = data.get('risk_level', 'UNKNOWN')
    checks = data.get('checks', [])
    passed = sum(1 for c in checks if c['passed'])
    failed = len(checks) - passed

    summary = [
        ['Score', 'Risk Level', 'Passed', 'Failed'],
        [f"{score}/100", risk, str(passed), str(failed)],
    ]
    t = Table(summary, colWidths=[4*cm, 4*cm, 4*cm, 4*cm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.black),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BACKGROUND', (0, 1), (-1, 1), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    categories = {
        'headers': 'HTTP Security Headers',
        'transport': 'Transport Security',
        'ssl': 'SSL Certificate',
        'ports': 'Open Ports',
    }

    by_cat = {}
    for c in checks:
        cat = c.get('category', 'other')
        by_cat.setdefault(cat, []).append(c)

    for key, label in categories.items():
        cat_checks = by_cat.get(key, [])
        if not cat_checks:
            continue
        story.append(Paragraph(label, heading))
        story.append(HRFlowable(width="100%", thickness=0.5, spaceAfter=4))

        rows = [['Check', 'Status', 'Severity', 'Detail']]
        for c in cat_checks:
            rows.append([
                Paragraph(c['name'], body),
                'PASS' if c['passed'] else 'FAIL',
                c.get('severity', ''),
                Paragraph(c.get('detail', '')[:100], body),
            ])

        ct = Table(rows, colWidths=[4.5*cm, 2*cm, 2.5*cm, 7.5*cm])
        ct.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.black),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('ALIGN', (1, 0), (2, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')]),
        ]))
        for i, c in enumerate(cat_checks, start=1):
            color = colors.green if c['passed'] else colors.red
            ct.setStyle(TableStyle([('TEXTCOLOR', (1, i), (1, i), color),
                                    ('FONTNAME', (1, i), (1, i), 'Helvetica-Bold')]))
        story.append(ct)
        story.append(Spacer(1, 0.3*cm))

    failed_checks = [c for c in checks if not c['passed'] and c.get('recommendation')]
    if failed_checks:
        story.append(Paragraph("Recommendations", heading))
        story.append(HRFlowable(width="100%", thickness=0.5, spaceAfter=4))
        for c in failed_checks:
            story.append(Paragraph(f"• <b>{c['name']}</b>: {c['recommendation']}", body))
            story.append(Spacer(1, 0.15*cm))

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5))
    story.append(Paragraph("Generated by SecScan · For authorized testing only.", 
                           ParagraphStyle('f', fontSize=7, textColor=colors.grey)))

    doc.build(story)
    return buffer.getvalue()