# Generated by Django 6.0.6 on 2026-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField(default=0)),
                ("risk_level", models.CharField(max_length=20)),
                ("results_json", models.TextField(default="{}")),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
    ]
